:GRAMMAR
start ::= expr ;

?expr ::= expr "+" term : addition
| expr "-" term : subtraction
| term ;

?term ::= term "*" factor : multiplication 
| term "/" factor : division
| factor ;

?factor ::= NUM 
| "(" expr ")" ;

:TERMINALS
NUM /[0-9]+/ ;
SPC /[ \t\n\r]+/ ;

.IGNORE SPC ;
